services:
  faucet:
    container_name: faucet
    image: scalar/faucet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - .env:/app/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"  